{% set version = "0.19.3" %}

package:
  name: wgpu-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wgpu/wgpu-{{ version }}.tar.gz
  sha256: 1b5bb2b86b82fa89a8de4d624801929abe033bc639363d59897e3f3752ad6957
  patches:
    # - 0001-Use-conda-forge-s-system-libraries-for-wgpu-native.patch
    # https://github.com/pygfx/wgpu-py/pull/666
    - 666-better_patch_for_native.patch
    - no_check_for_version.patch
    - no_hatchling.patch

build:
  noarch: python
  script:
    # Don't vendor the headers, let them get pulled in by webgpu-headers at runtime
    - rm wgpu/resources/webgpu.h   # [unix]
    - rm wgpu/resources/wgpu.h     # [unix]
    - del wgpu\resources\webgpu.h  # [win]
    - del wgpu\resources\wgpu.h    # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cffi >=1.15.0
    - rubicon-objc >=0.4.1  # [osx]
    - sniffio
    # https://github.com/pygfx/wgpu-py/blob/main/wgpu/backends/wgpu_native/__init__.py
    - wgpu-native 22.1.0.5
    # Keep webgpu-headers in sync with wgpu-native
    # For newer versions (after 22.1.0.5) we have a run_constraint
    - webgpu-headers 0.0.0.2024.6.12
    - __linux  # [linux]
    - __win    # [win]
    - __osx    # [osx]
  run_constrained:   # [osx]
    # seems like rubicon-objc doesn't support pypy...
    - python *=*_cpython    # [osx]

test:
  imports:
    - wgpu
    - wgpu.backends.wgpu_native
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pygfx/wgpu-py
  summary: next generation GPU API for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
