{% set version = "0.19.2" %}

package:
  name: wgpu-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wgpu/wgpu-{{ version }}.tar.gz
  sha256: 157483bed854c2ebb7988fc62d3d7e22568d5fc51627765ad5fde798b4a45c97
  patches:
    - 0001-Use-conda-forge-s-system-libraries-for-wgpu-native.patch
    - no_check_for_version.patch
    - no_hatchling.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cffi >=1.15.0
    - rubicon-objc >=0.4.1  # [osx]
    # https://github.com/pygfx/wgpu-py/blob/main/wgpu/backends/wgpu_native/__init__.py
    - wgpu-native 22.1.0.5
    # Keep webgpu-headers in sync with wgpu-native
    # For newer versions we have a run_constraint
    - webgpu-headers 0.0.0.2024.6.12
    - __linux  # [linux]
    - __win    # [win]
    - __osx    # [osx]
  run_constrained:   # [osx]
    # seems like rubicon-objc doesn't support pypy...
    - python *=*_cpython    # [osx]

test:
  imports:
    - wgpu
    - wgpu.backends.wgpu_native
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pygfx/wgpu-py
  summary: next generation GPU API for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
