{% set python_min = "3.10" %}
{% set version = "0.28.1" %}

package:
  name: wgpu-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wgpu/wgpu-{{ version }}.tar.gz
  sha256: 4393962cba6b22ecc93b5709acddfad17b03fce9495d43729705ea882f694af1

build:
  noarch: python
  script_env:
    # Avoid pulling in any binary files during the hatchling building process
    # https://github.com/pygfx/wgpu-py/pull/669
    - WGPU_PY_BUILD_NOARCH=1
  script:
    # Don't vendor the headers, let them get pulled in by webgpu-headers at runtime
    - rm wgpu/resources/webgpu.h   # [unix]
    - rm wgpu/resources/wgpu.h     # [unix]
    - del wgpu\resources\webgpu.h  # [win]
    - del wgpu\resources\wgpu.h    # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cffi >=1.15.0
    - rubicon-objc >=0.4.1  # [osx]
    - sniffio
    # https://github.com/pygfx/wgpu-py/blob/main/wgpu/backends/wgpu_native/__init__.py
    - wgpu-native 27.0.2.0
    - webgpu-headers
    # Check the pypi package requirement
    # to keep render canvas in sync
    # https://github.com/pygfx/wgpu-py/blob/main/pyproject.toml
    - rendercanvas >=2.4
    - __linux  # [linux]
    - __win    # [win]
    - __osx    # [osx]

test:
  imports:
    - wgpu
    - wgpu.backends.wgpu_native
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pygfx/wgpu-py
  summary: next generation GPU API for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
